### PR TITLE
Fix unknown $rc error

### PR DESCRIPTION
**Pull request by WyriHaximus**
When trying to implement this package I ran into an situation where `$rc` isn't set and raises an error. This PR fixes that and includes a test case covering that bug.

### CODE REVIEW

**Comment by alexdruhet** [comment]
Hi, I'm facing same error trying to minify an empty json string: `{}`.

**Comment by t1st3** [comment]
@WyriHaximus thanks for this fix, and sorry for the delay I took to merge it... Best

**Comment by WyriHaximus** [comment]
@t1st3 Thanks 👍 ! Any change for a release, it's been almost four years?

**Comment by t1st3** [comment]
Yep, a new release is definitely on my mind, but yet, the merged PR doesn't pass the Travis-Ci suite, for compatibility issues regarding recent PHP versions...
More here: https://travis-ci.org/t1st3/php-json-minify/builds/646553652?utm_source=github_status&utm_medium=notification
I hope this can be fixed quickly; then we'll be able to cut a new release safely.

**Comment by WyriHaximus** [comment]
Looking at that error it's not related but I'll have a look for you :).

**Comment by t1st3** [comment]
Looks like there is a conflict with PhpUnit version:

> This version of PHPUnit is supported on PHP 7.1 and PHP 7.2.
> You are using PHP 7.0.33 (/home/travis/.phpenv/versions/7.0.33/bin/php).

**Comment by WyriHaximus** [comment]
> Looks like there is a conflict with PhpUnit version:
> 
> > This version of PHPUnit is supported on PHP 7.1 and PHP 7.2.
> > You are using PHP 7.0.33 (/home/travis/.phpenv/versions/7.0.33/bin/php).

@t1st3 #25 is now full on green :tada:

**Pull request merged**
