### PR TITLE
Test against all support and currently available PHP versions

### PR DESCRIPTION
**Pull request by WyriHaximus**
Follow up for https://github.com/t1st3/php-json-minify/pull/23#issuecomment-582893111, haven't tested this but will update it to get it to work :)

### CODE REVIEW

**Comment by t1st3** [comment]
Wow, thanks a lot @WyriHaximus 
I'll try to cut a new release today or tomorrow based on this work

**Comment by WyriHaximus** [comment]
No problem, can also modernise the code a bit before the release if you want.

**Comment by t1st3** [comment]
sure, please go ahead!

**Comment by WyriHaximus** [comment]
How far should I go ahead with that? Do you want to stay on the currently supported PHP version or can I bump it to something newer?

**Pull request merged**
